name: All Checked Verifier

on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize]
    paths:
      - '**/code.py'
jobs:
  enforce-label:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          public_api_views:
            - '**/code.py'
    - if: steps.changes.outputs.public_api_views == 'true'
      uses: yogevbd/enforce-label-action@2.1.0
      with:
        REQUIRED_LABELS_ALL: "checked-everything"
        REQUIRED_LABELS_ALL_DESCRIPTION: "Make sure we have checked everything and once done, add label 'checked-everything' to this PR."